// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylDVV62eUIglaWdGpeY1sW-j_ytTyIFo',
    appId: '1:447639644886:web:75b5762b2c8b9c3897b777',
    messagingSenderId: '447639644886',
    projectId: 'dht112-d7452',
    authDomain: 'dht112-d7452.firebaseapp.com',
    storageBucket: 'dht112-d7452.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAN67o5Et9RrV_E40B6I59ozis9uVCX9ao',
    appId: '1:447639644886:android:f3f6312d383c82f697b777',
    messagingSenderId: '447639644886',
    projectId: 'dht112-d7452',
    storageBucket: 'dht112-d7452.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6hA5IaWuoPOTR-jsZMVfmG8IzS-pm9WM',
    appId: '1:447639644886:ios:85b0809765166b7497b777',
    messagingSenderId: '447639644886',
    projectId: 'dht112-d7452',
    storageBucket: 'dht112-d7452.appspot.com',
    iosBundleId: 'com.example.historialExit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6hA5IaWuoPOTR-jsZMVfmG8IzS-pm9WM',
    appId: '1:447639644886:ios:85b0809765166b7497b777',
    messagingSenderId: '447639644886',
    projectId: 'dht112-d7452',
    storageBucket: 'dht112-d7452.appspot.com',
    iosBundleId: 'com.example.historialExit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAylDVV62eUIglaWdGpeY1sW-j_ytTyIFo',
    appId: '1:447639644886:web:37e61c3971a3b3ba97b777',
    messagingSenderId: '447639644886',
    projectId: 'dht112-d7452',
    authDomain: 'dht112-d7452.firebaseapp.com',
    storageBucket: 'dht112-d7452.appspot.com',
  );
}
